package org.example.model;

import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Relationship;

import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;

@Node("SeismicEvent")
public class Event {

    /**
     * Deterministic MD5 ID set by replicas — not generated by the backend.
     * Used as the Neo4j node identity property (eventId).
     */
    @Id
    private String eventId;

    private ZonedDateTime timestamp;
    private double frequency;
    private Classification classification;
    private boolean confirmed;

    // Scalar copies of sensor/region data — stored directly on the node by replicas
    // for efficient filtering without traversing relationships on every query.
    private String sensorId;
    private String region;
    private double lat;
    private double lon;

    // ── Graph relationships ──────────────────────────────────────────────────
    @Relationship(type = "DETECTED", direction = Relationship.Direction.INCOMING)
    private Sensor sensor;

    @Relationship(type = "OCCURRED_IN", direction = Relationship.Direction.OUTGOING)
    private Region occurredIn;

    /** One entry per replica that independently detected and reported this event. */
    @Relationship(type = "REPORTED", direction = Relationship.Direction.INCOMING)
    private List<ReportedBy> reportedBy = new ArrayList<>();

    protected Event() {}

    public Event(String eventId, ZonedDateTime timestamp, double frequency,
                 Classification classification, double lat, double lon,
                 String sensorId, String region, Sensor sensor, Region occurredIn) {
        this.eventId = eventId;
        this.timestamp = timestamp;
        this.frequency = frequency;
        this.classification = classification;
        this.lat = lat;
        this.lon = lon;
        this.sensorId = sensorId;
        this.region = region;
        this.sensor = sensor;
        this.occurredIn = occurredIn;
        this.confirmed = false;
    }

    public String getEventId() { return eventId; }

    public ZonedDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(ZonedDateTime timestamp) { this.timestamp = timestamp; }

    public double getFrequency() { return frequency; }
    public void setFrequency(double frequency) { this.frequency = frequency; }

    public Classification getClassification() { return classification; }
    public void setClassification(Classification classification) { this.classification = classification; }

    public boolean isConfirmed() { return confirmed; }
    public void setConfirmed(boolean confirmed) { this.confirmed = confirmed; }

    public String getSensorId() { return sensorId; }
    public void setSensorId(String sensorId) { this.sensorId = sensorId; }

    public String getRegion() { return region; }
    public void setRegion(String region) { this.region = region; }

    public double getLat() { return lat; }
    public void setLat(double lat) { this.lat = lat; }

    public double getLon() { return lon; }
    public void setLon(double lon) { this.lon = lon; }

    public Sensor getSensor() { return sensor; }
    public void setSensor(Sensor sensor) { this.sensor = sensor; }

    public Region getOccurredIn() { return occurredIn; }
    public void setOccurredIn(Region occurredIn) { this.occurredIn = occurredIn; }

    public List<ReportedBy> getReportedBy() { return reportedBy; }
    public void setReportedBy(List<ReportedBy> reportedBy) { this.reportedBy = reportedBy; }
}

