services:
  neo4j:
    image: neo4j:5
    restart: on-failure
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data
      - ./init:/var/lib/neo4j/import
    networks:
      - gladiators-net

volumes:
  neo4j-data:

networks:
  gladiators-net:
